# Generated by Django 3.2.20 on 2025-02-27 21:10

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editpage',
            name='slider_image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
