# Generated by Django 5.0.9 on 2025-07-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editpage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='editpage',
            name='heading',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainprogrames',
            name='programe_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainprogrames',
            name='programe_objective1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainprogrames',
            name='programe_objective2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainprogrames',
            name='programe_objective3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainprogrames',
            name='programe_objective4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secondsectionbox',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secondsectionicon',
            name='text',
            field=models.TextField(),
        ),
    ]
