# Generated by Django 3.2.20 on 2025-02-06 23:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProgrames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programe_name', models.CharField(choices=[('Programme1', 'Programe | Programme1'), ('Programme2', 'Programe | Programme2'), ('Programme3', 'Programe | Programme3'), ('Programme4', 'Programe | Programme4')], max_length=100, unique=True)),
                ('programe_description', ckeditor.fields.RichTextField()),
                ('programe_objective1', ckeditor.fields.RichTextField()),
                ('programe_objective2', ckeditor.fields.RichTextField()),
                ('programe_objective3', ckeditor.fields.RichTextField()),
                ('programe_objective4', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
