# Generated by Django 3.2.20 on 2025-02-27 22:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_editpage_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', ckeditor.fields.RichTextField()),
                ('title', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Second Section',
                'verbose_name_plural': 'Second Sections',
            },
        ),
        migrations.CreateModel(
            name='SecondSectionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Second Section Box',
                'verbose_name_plural': 'Second Section Boxes',
            },
        ),
        migrations.CreateModel(
            name='SecondSectionIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(choices=[('icon-vegetable', 'Food Icon'), ('icon-water-1', 'Water Icon'), ('icon-stethoscope', 'Medical Icon')], max_length=50)),
                ('text', ckeditor.fields.RichTextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Second Section Icon',
                'verbose_name_plural': 'Second Section Icons',
                'ordering': ['order'],
            },
        ),
    ]
