# Generated by Django 5.0.9 on 2025-07-21 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_program_sitesettings_teammember_pagesection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us Page'), ('programs', 'Programs Page'), ('team', 'Our Team Page'), ('contact', 'Contact Us Page')], help_text='Which page this content appears on', max_length=50)),
                ('content_type', models.CharField(choices=[('home_hero_main', 'Home: Main Hero Section'), ('home_hero_secondary', 'Home: Secondary Hero Section'), ('home_hero_tertiary', 'Home: Third Hero Section'), ('home_about_preview', 'Home: About Us Preview'), ('home_mission_statement', 'Home: Mission Statement'), ('home_vision_statement', 'Home: Vision Statement'), ('home_volunteer_section', 'Home: Volunteer Call-to-Action'), ('home_program_1', 'Home: Featured Program 1'), ('home_program_2', 'Home: Featured Program 2'), ('home_program_3', 'Home: Featured Program 3'), ('about_main_content', 'About: Main About Us Content'), ('about_mission_detailed', 'About: Detailed Mission Statement'), ('about_vision_detailed', 'About: Detailed Vision Statement'), ('about_history', 'About: Our History'), ('about_values', 'About: Our Values'), ('programs_overview', 'Programs: Overview Section'), ('programs_goddess_care', 'Programs: Goddess Care Initiative'), ('programs_reach', 'Programs: Our Reach'), ('programs_impact', 'Programs: Impact Statistics'), ('team_kelly', 'Team: Kelly Wanjiku Profile'), ('team_elsie', 'Team: Elsie Muthoni Profile'), ('team_loise', 'Team: Loise Njeri Profile'), ('team_overview', 'Team: Team Overview'), ('contact_main', 'Contact: Main Contact Information'), ('contact_office', 'Contact: Office Details'), ('contact_form_intro', 'Contact: Contact Form Introduction'), ('footer_content', 'Global: Footer Content'), ('header_announcement', 'Global: Header Announcement')], help_text='Specific section of the page', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Internal title for admin reference', max_length=200)),
                ('heading', models.TextField(blank=True, help_text='Main heading that appears on the website')),
                ('content', models.TextField(blank=True, help_text='Main content with rich text formatting')),
                ('image', models.ImageField(blank=True, help_text='Image for this content section', null=True, upload_to='website_content/')),
                ('is_active', models.BooleanField(default=True, help_text='Show this content on the website')),
                ('display_order', models.IntegerField(default=0, help_text='Order of appearance (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='Last person to edit this content', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Content',
                'verbose_name_plural': 'Website Content',
                'ordering': ['page', 'display_order', 'content_type'],
            },
        ),
    ]
