# Generated by Django 3.2.20 on 2025-03-13 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_editpage_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
