# Generated by Django 3.2.20 on 2025-03-13 11:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_editpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editpage',
            name='heading',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
