# Generated by Django 3.2.20 on 2025-04-02 22:33

from django.db import migrations





def handle_null_users(apps, schema_editor):
    # Get the historical models
    User = apps.get_model('auth', 'User')
    Post = apps.get_model('blogapp', 'Post')
    
    # Get or create admin user
    admin_user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'is_staff': True,
            'is_superuser': True,
            'email': 'admin1@livegreatfoundation.org'
        }
    )
    
    # Update posts with NULL user
    Post.objects.filter(user__isnull=True).update(user=admin_user)

class Migration(migrations.Migration):
    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(handle_null_users, reverse_code=migrations.RunPython.noop),
    ]