"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jqx3e+sq2(sja+kuxr6(t5oijbe6(9jaf!1ieat0raf0nb&w=w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'users.apps.UsersConfig',
    'blogapp',
    'events',
    'notifications',
    'django_prose_editor',
    'taggit',
    'import_export',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'

WHITENOISE_MANIFEST_STRICT = False
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.rhphjdabjfllajcwrbra',
        'PASSWORD': 'LGFweb2025!keke',
        'HOST': 'aws-0-eu-central-1.pooler.supabase.com',
        'PORT': '6543',
        'OPTIONS': {
            'sslmode': 'require',
            # Supabase-specific optimizations
            'connect_timeout': 10,
            'options': '-c default_transaction_isolation=read_committed'
        },
        # Connection pooling settings for Supabase
        'CONN_MAX_AGE': 600,  # 10 minutes
        'CONN_HEALTH_CHECKS': True,
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'  # This is the correct time zone for East Africa (UTC+3)

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/



# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Additional directories to look for static files (e.g., your assets directory)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Directory for static files during development
]

# WhiteNoise settings for serving static files

# Media files (user-uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"# Template settings

## For media files
UPLOADCARE = {
  # Don’t forget to set real keys when it gets real :)

  'pub_key': '18ad19435c41077ca842',
  'secret': 'b27f8995d2e4b66cbf02',
}

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "Live Great Foundation Admin",
    "SITE_HEADER": "Live Great Foundation",
    "SITE_URL": "/",
    "SITE_SYMBOL": "speed",  # symbol from icon set
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "196 181 253",
            "400": "147 51 234",
            "500": "124 58 237",
            "600": "109 40 217",
            "700": "91 33 182",
            "800": "76 29 149",
            "900": "59 7 100",
            "950": "35 25 74"
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
}



# Django Prose Editor Configuration
PROSE_EDITOR = {
    'toolbar': [
        'bold', 'italic', 'underline', 'strikethrough',
        '|', 'heading1', 'heading2', 'heading3',
        '|', 'bulletList', 'orderedList',
        '|', 'link', 'image',
        '|', 'blockquote', 'codeBlock',
        '|', 'undo', 'redo'
    ],
    'types': [
        {
            'key': 'default',
            'toolbar': [
                'bold', 'italic', 'underline',
                '|', 'heading1', 'heading2', 'heading3',
                '|', 'bulletList', 'orderedList',
                '|', 'link', 'image',
                '|', 'blockquote'
            ]
        }
    ]
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For testing
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # For production
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 60
EMAIL_HOST_USER = 'dedeexpeditions@gmail.com'
EMAIL_HOST_PASSWORD = 'roqu frlt wvof rqxk'
DEFAULT_FROM_EMAIL = 'Live Great Foundation Technical Team <dedeexpeditions@gmail.com>'

# SSL Configuration for email
import ssl
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None

# Email Notification Settings
LGF_ADMIN_EMAIL = 'info@livegreatfoundation.org'
LGF_NOTIFICATION_ENABLED = True