# Generated by Django 5.0.9 on 2025-07-21 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task or update title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the task/update')),
                ('notification_type', models.CharField(choices=[('task_completion', 'Task Completion'), ('system_update', 'System Update'), ('feature_release', 'Feature Release'), ('maintenance', 'Maintenance'), ('security_update', 'Security Update')], default='task_completion', max_length=20)),
                ('recipient_email', models.EmailField(default='info@livegreatfoundation.org', max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('email_content', models.TextField(help_text='HTML email content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed')),
                ('features_delivered', models.JSONField(default=list, help_text='List of key features or improvements delivered')),
                ('technical_details', models.JSONField(default=dict, help_text='Technical implementation details')),
                ('next_steps', models.TextField(blank=True, help_text='Recommended next steps or actions')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
